### PR TITLE
Revise .gitignore and Do Website-Exercise II

### PR DESCRIPTION
**Pull request by win911**

### CODE REVIEW

**Comment by hsiaoyi0504** [comment]
It's really a issue
I also found that XD

**Comment by TonyPythoneer** [comment]
When the PR is accepted and completes, you should do PR for your local repo in order to get the newest repo and update yours.

**Comment by hsiaoyi0504** [comment]
No, I think it's a bug that in original `.gitignore` file.
A `*` is missing before `.sqlite`
You can check the `develop` branch and `master` branch

**Comment by TonyPythoneer** [comment]
@hsiaoyi0504  Oh, I see. It's my mistake. XD
I missed type `*` before `.sqlite`, otherwise `.gitignore` will consider it's a file, not for `.sqlite` extension.

**Pull request merged**
